spring.application.name=backend-servicex
server.port=8081

# Database Connection
spring.datasource.url=jdbc:postgresql://restaurant-admin-db.c3oec40wsyuk.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=**Resto123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool Settings (recommended)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# I faced issues with Hibernate metadata lookup delays
# Add a startup timeout so it doesn't hang forever
spring.datasource.hikari.initialization-fail-timeout=1

# Help Hibernate find the metadata faster
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=flavorframe6@gmail.com
spring.mail.password=owmn doli asba clup
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2 (use env vars)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

# Google OAuth2 (use env vars)
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# mvn
spring.profiles.active=local

# =========================
# FILE UPLOAD CONFIG (HARD LIMIT)
# =========================
# This blocks large uploads BEFORE your controller/service runs.
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Menu item photo validation (used server-side in MenuItemImageStorageService)
file.upload.max-photo-size-bytes=5242880

# Custom upload directories
file.upload.logo-dir=uploads/logos
file.upload.photo-dir=uploads/photos